source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'IAPHelper_Example' do
  pod 'IAPHelper', :path => '../'

  target 'IAPHelper_Tests' do
    inherit! :search_paths

    
  end
end
